export enum OriginMethod {
    GETAPPS      = 'GETAPPS',
    GETCSVAPP    = 'GETCSVAPP', 
    GETDOWNLOAD  = 'GETDOWNLOAD',
    GETLANGUAGES = 'GETLANGUAGES',
    POSTSAVEPDF  = 'POSTSAVEPDF', 
    POSTSAVEFILE = 'POSTSAVEFILE',
    UPDATESTATUS = 'UPDATESTATUS', 
}