export enum OriginMethod {
    DELETEUSERS  = 'DELETEUSERS',
    GETUSER      = 'GETUSER',
    GETUSERS     = 'GETUSERS',
    UPDATEUSER   = 'UPDATEUSER',
    GETPOSITIONS = 'GETPOSITIONS',
    GETINFOORG   = 'GETINFOORG',
    GETMANAGER   = 'GETMANAGER',
    POSTPASSWORD = 'POSTPASSWORD' 
}